language: python
python:
    - 3.6

install:
    - pip3 install scipy
    - pip3 install numpy
    - pip3 install scikit-learn
    - pip3 install matplotlib
    - pip3 install Theano
    - pip3 install Lasagne
    - pip3 install --upgrade https://github.com/Lasagne/Lasagne/archive/master.zip
    - pip3 install --upgrade https://github.com/Theano/Theano/archive/master.zip
script:
    - python3 run_defense.py --n_epoch=5 -d recons --rev
    - python3 run_defense.py --n_epoch=5 -d retrain
    - python3 strategic_svm.py
    #- python run_defense.py --n_epoch=5 -d retrain -dr kernel-pca




# after_success:
#     -

# This reportedly works around an issue downloading packages from pypi on
# travis.  Consider removing this after the underlying issue is fixed.
# https://github.com/travis-ci/travis-ci/issues/2389
sudo: false

matrix:
    fast_finish: true
